server:
  port: 8082

spring:
 mvc:
   view:
     prefix: /WEB-INF/views/
     suffix: .jsp




#server.port = 8080
#spring.mvc.view.prefix = /WEB-INF/views/
#spring.mvc.view.suffix = .jsp
#spring.rabbitmq.host = localhost
#spring.rabbitmq.port = 5672